### ISSUE TITLE
On-demand (or scheduled) re-sync

### ISSUE THREAD

**Issue by cjchristopher** [catmanjan/anutimetable#283]
Rather than explicit requests or monitoring for resynchronisation, it might be worth automating it (once a day? week?), at least (especially) until semesters start in earnest.

Side note - current state as of 01/02/19 is out of date.

**Comment by mdchia** [comment]
I am sadly lacking a server to do so atm. I just resynced it though, hope that helps!

**Comment by tagpro** [comment]
@mdchia How about a firebase function to do so? I am not sure about the pricing but the basic plan should help you get a function up. You can host on firebase as well.

**Comment by BishopOfTurkey** [comment]
@tagpro Scraping outside of the ANU network is slow is slow so. Maybe a raspberry pi setup on campus somewhere might work.

**Comment by catmanjan** [comment]
i dont know if they do it anymore, but you use to be able to run things in partch under your account

**Comment by mdchia** [comment]
Firebase basic plan only allows connections to Google services as far as I can tell, unfortunately. Slow is fine as long as it doesn't time out or something in the process, I think? And I don't have a partch account atm but the last time I tried the partch scripts didn't work anymore.

**Comment by brendanmeyer** [comment]
The current timetable is out of date. For example, I can't see COMP1100 5pm tutorial on Tuesdays for Semester 2.

Maybe it could be an idea that allows a user to re-sync a particular class. And maybe limit it to 1 or a few times a day.

**Comment by BishopOfTurkey** [comment]
Something to look into. The way classes are stored might need to changed. Introduces a server to the project though. Not sure if xss would be a problem if done client side.

**Comment by brendanmeyer** [comment]
sorry, I was more referring to the hosted version, rather than the offline compatible version

**Comment by KitKat27** [comment]
BUSN7008 opens a new tutorial, could yall update? Big thanks!

**Comment by mdchia** [comment]
done!

**Comment by KitKat27** [comment]
> done!


Checked just now, still not available sor. Umm it's on Wed 3-4pm, newly opened. Appreciate if u could check again.=)

**Comment by BishopOfTurkey** [comment]
@KitKat27 Sorry something went wrong with the merging. Should be working now

**Comment by brendanmeyer** [comment]
Could you please do another Pull, it is out of sync again. Thank you in advance

**Comment by BishopOfTurkey** [comment]
Another solution to this would be using github actions

**Comment by brendanmeyer** [comment]
added a PR for now #354

**Comment by BishopOfTurkey** [comment]
Implemented using github actions. Should scrape daily

**Comment by brendanmeyer** [comment]
Hey @BishopOfTurkey 

That is great, though, unfortunately, it doesn't look to be working.

The webpage still says "Course list updated on 13th of February, 2021."
And the course I am seeing incorrect this semester is COMP2300, specifically, Lec0B which should show as 13.30->15.00 on Mondays (correct on timetabling.anu.edu.au) and currently shows as Thursday.

Thank you again for your work.
Brendan

**Comment by BishopOfTurkey** [comment]
Thanks @brendanmeyer. Should be working now.

**Comment by brendanmeyer** [comment]
Great, looks to be updated now :) thanks
And I feel this is a great feature.
