### ISSUE TITLE
Table not refreshing properly

### ISSUE THREAD

**Issue by Sembrani** [catmanjan/anutimetable#64]
Empty cells appear when tutorials which clash with others are selected, when the width of the column is reduced when all clashes in a day are removed, disfiguring the table. Can be fixed with a page refresh.

**Comment by samyex6** [comment]
Do you remember the order you clicked to trigger that bug?
E.g. COMP1110 -> COMP1710 -> COMP2100 -> Clicked 'Choose' on 1710 Tue 9am tut -> cleared COMP2100 courses.

**Comment by Sembrani** [comment]
Fastest way I've found to reproduce:

ENGN1217, ENGN1218, ENGN1219 -> Chose ENGN2217 0900 - 1200 Computer Laboratory1 / 1 and ENGN2217 1400 - 1700 Practical1 / 3

**Comment by samyex6** [comment]
The issue should now be resolved, pls try again :tada:

**Comment by Sembrani** [comment]
Still an issue. 
![issue](https://cloud.githubusercontent.com/assets/9014982/12871078/860d9a20-cdbb-11e5-8ac5-80981553c6ab.png)

**Comment by samyex6** [comment]
ah that, that's just some vacant slots after you delete contents inside those grids, will deal with that later.
but this issue should be fixed:
![capture](https://cloud.githubusercontent.com/assets/13520523/12871210/760f116a-cdc2-11e5-8d94-d189b016533c.PNG)

**Comment by Sembrani** [comment]
awesome. You guys are doing a great job with this website.

**Comment by samyex6** [comment]
thanks :)

**Comment by catmanjan** [comment]
For now users can just refresh the page to remove the artefacts
